type Contestant @aws_cognito_user_pools @aws_api_key {
    gameId: Int!
    login: String!
    name: String!
    organization: String
    score: Int!
}

type Game {
    gameId: Int!
    emcee: String!
    title: String!
    categories: [Category!]
    contestants: [Contestant!]
}

type Category {
    gameId: Int!
    catgId: Int!
    categoryName: String!
    questions: [Question!]
}

type Question {
    catgId: Int!
    quesId: Int!
    points: Int!
    question: String!
    answer: String!
    state: StateEnum!
    nominees: [Nominee!]
}

type Nominee @aws_cognito_user_pools @aws_api_key {
    quesId: Int!
    login: String!
    timebuzzed: Int!
}

enum StateEnum {
    ready
    display
    open
    closed
}

type Query {
    listGames: [Game!]
    listGamesByEmcee(emcee: String!): [Game!]
    getGameById(gameId: Int!): Game
    getQuestionByCatgIdQuesId(catgId: Int!, quesId: Int!): Question
    getQuestionByQuesId(quesId: Int!): Question
    listContestants: [Contestant!]!  @aws_cognito_user_pools @aws_api_key
}

type Mutation {
    setQuestionState(catgId: Int!, quesId: Int!, state: StateEnum!): Question!
    joinGame(gameId: Int!): Contestant! @aws_cognito_user_pools @aws_api_key
    nominateContestant(quesId: Int!, login: String!): Nominee! @aws_cognito_user_pools @aws_api_key
    removeNominee(quesId: Int!, login: String!): Nominee!
    setContestantScore(gameId: Int!, login: String!, newScore: Int!): Contestant!
}

type Subscription {
    questionStateChange: Question!
	    @aws_subscribe(mutations: [ "setQuestionState" ])
    nominateContestant(quesId: Int!): Nominee!
        @aws_subscribe(mutations: [ "nominateContestant" ])
    removeNominee(quesId: Int!): Nominee!
        @aws_subscribe(mutations: [ "removeNominee" ])
    setContestantScore(gameId: Int!): Contestant!
        @aws_subscribe(mutations: [ "setContestantScore" ])
}

schema {
    query: Query
    mutation: Mutation
	subscription: Subscription
}
